### ISSUE TITLE
Molmer-Sorensen frequency model: improve heuristics for scans not centred on resonance

### ISSUE THREAD

**Issue by AUTProgram** [OxIonics/ionics_fits#159]
When we probe two-qubit gate dynamics, we typically start by scanning the gate detuning over a wide range, such that the scan contains the line of symmetry (where mode is driven on resonance). In this case, the `MolmerSorensenFreq.estimate_parameters()` method works fine because it looks for the symmetry point. However, sometimes we also just scan the gate detuning over a narrower range around the loop closure. In this case, the fit gives garbage, see below for an example.
![image](https://github.com/OxIonics/ionics_fits/assets/18437684/849ffe62-1669-4756-8310-73df45cf70d2)

For now, I'm handling this issue by specifying a user estimate for `w_0` manually depending on the scan range. If we can think of a simple heuristic that helps with this, probably worth adding to the estimation procedure directly rather than relying on the user.

**Comment by hartytp** [comment]
Chatted about this IRL. I think this is a "won't fix" issue. Motivations:
- doing a narrow scan around a specific revival is something one generally only does when one knows the gate detuning relatively accurately so it's easy to supply an accurate `user_estimate`. As such there isn't a huge amount of value to be had in getting an accurate heuristic here
- I suspect it would be pretty hard to write a general-purpose heuristic which could figure out that we're doing a narrow scan around a specific revival. To make that work, we'd probably have to hard code a lot of assumptions, so this would be a niche special-casing

Given the above, this feels out of scope for `ionics_fits` and is best handled by users giving the fit an initial guess
