### ISSUE TITLE
Sinc2 online fit failing

### ISSUE THREAD

**Issue by saking2** [OxIonics/ionics_fits#84]
The `Sinc2` online fit is failing with the message:

```
ionics_fragments.ndscan_extensions.analysis:Exception during online fit
ValueError: Residuals are not finite in the initial point.
```

The post-scan fit is returning meaningful results. The online fit for a `RabiFlopFreq` model with the same data quality works fine.

**Comment by hartytp** [comment]
That's interesting. Do you have a dataset where it failed?

**Comment by hartytp** [comment]
@saking2 I need more information than this to track the bug down. Can you give me anything else to go on?

**Comment by hartytp** [comment]
I think this is resolve
