### ISSUE TITLE
Improve documentation for models in `containers`

### ISSUE THREAD

**Issue by AUTProgram** [OxIonics/ionics_fits#91]
I had a quick first look at the new model container classes, but from the existing docstrings it's not clear to me what the purpose of each container model is. For example, what does `"aggregating one or more models" mean? Is a repeated model just a convenience class to use the same model on different data (which is what "repeated" implies to me) or does it provide functionality that could not be achieved by using separate models? I'll have a look at source code to find out, but I think it's a sign that the documentation can be improved if the user starts reading source code.

**Comment by hartytp** [comment]
More broadly, I see the purpose of docstrings as being largely to document the interface and how the parameters are used. I'm reading your question here as being more about looking for examples, which I find is often best outside of docstrings. For this, I've been using the readme. Specifically, I wonder if https://github.com/OxIonics/ionics_fits#containers answers your questions?

> Is a repeated model just a convenience class to use the same model on different data (which is what "repeated" implies to me) or does it provide functionality that could not be achieved by using separate models?

A bit of both. It's largely convenience, but the docstring already mentions a couple of features which would not be possible using independent models: common parameters, calculating statistical quantities for results automatically (e.g. what is the mean value of this parameter across the repetitions?)

**Comment by hartytp** [comment]
If you have concrete suggestions for what you think would be helpful, do feel free to open a PR.
